### PR TITLE
b21user worked on tc002 awesomely

### PR DESCRIPTION
**Pull request by SF001User**
Share your insight my awesome team

### CODE REVIEW

**Comment by Innakqa** [comment]
Good job!

**Comment by ayseca** [comment]
great!

**Comment by ayseca** [comment]
i love this project!

**Comment by watsgucci** [comment]
hey

**Comment by watsgucci** [comment]
i see it now but I just dont understand what this part means tbh

**Review by watsgucci — APPROVED** [review]

**Pull request merged**
